In [2]:
import numpy as np

In [4]:
np1 = np.array([1,2,3,4])

np2 = np.array([5,6,7,8])



In [6]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [10]:
listdata = [[1,2,3,4,5],
        [6,7,8,9,10]]


np8 = np.array(listdata)
print(np8.shape)
print(np8.ndim)
print(np8.size)

(2, 5)
2
10


In [12]:
np9 = np.arange(1,21)
print(np9)

np10 = np9.reshape(4,5)
print(np10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
np12 = np.genfromtxt('scores.csv', delimiter=',',skip_header=1)

print(np12)

[[ 1. 87. 85. 82.]
 [ 2. 92. 87. 90.]
 [ 3. 80. 91. 87.]
 [ 4. 78. 82. 95.]
 [ 5. 88. 89. 90.]
 [ 6. 82. 87. 88.]
 [ 7. 90. 92. 82.]
 [ 8. 87. 80. 90.]
 [ 9. 95. 78. 87.]
 [10. 90. 88. 95.]
 [11. 88. 89. 75.]
 [12. 82. 91. 66.]
 [13. 90. 82. 87.]
 [14. 87. 89. 92.]
 [15. 95. 87. 80.]
 [16. 90. 92. 78.]
 [17. 82. 80. 88.]
 [18. 90. 78. 93.]
 [19. 67. 87. 95.]
 [20. 91. 82. 88.]
 [21. 82. 81. 82.]
 [22. 79. 87. 90.]
 [23. 87. 92. 87.]
 [24. 92. 82. 95.]
 [25. 80. 90. 78.]
 [26. 78. 76. 91.]
 [27. 66. 90. 82.]
 [28. 89. 77. 89.]
 [29. 87. 95. 87.]
 [30. 73. 90. 92.]]
